# Generated by Django 5.0.6 on 2024-06-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_raca_logica_raca_logica_de_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='logica_de_criacao',
            field=models.TextField(),
        ),
    ]
